### ISSUE TITLE
Naming convention and PSR-2 rules 

### ISSUE THREAD

**Issue by bernard-ng** [itotafrica/Lushi-Food-Web#21]
I cannot contribute to the project because you guys did not define any contribution rules, your way of naming the variables and classes is specific to each developer, no PSR-2 or PSR-12 rule is respected ... how can we contribute?

**Comment by elviskankola1** [comment]
--

**Comment by elviskankola1** [comment]
i'am a simple contibutor and i'am execute my task. if you want to dev this, we can set rules and redo this app.

**Comment by bernard-ng** [comment]
redo the app ?? updating your code to a PSR-2 and PSR-12 one, is not so difficult, just use **squizlabs/php_codesniffer** to do that

**Comment by ljoboy** [comment]
You can just `refactor` what you think that it's not good and send a **pull request**

**Comment by elviskankola1** [comment]
i like this proposition, but i can good to speak with chief...

**Comment by elviskankola1** [comment]
go
